
server:
  servlet:
    context-path: /challenge/v1/star-wars
  port: 2222
  
logging:
  level:
    br:
      com:
        incubie:
          api:
            client: DEBUG
            
management:
  endpoints:
    web:
      base-path: /
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: false
      
spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
      
star-wars-api:
  base-url: https://swapi.dev/api